# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20160824_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
