# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-22 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20160822_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=0, max_length=200, verbose_name=b'Title'),
            preserve_default=False,
        ),
    ]
