# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_userevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='login',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userevent',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
